version: '3.8'

services:
  sw_team_7_nginx:
    image: nginx:latest
    container_name: sw_team_7_nginx
    ports:
      - "8620:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - sw_team_7_spring_blue
      - sw_team_7_spring_green

  sw_team_7_spring_blue:
    image: sw_team_7_spring:latest
    container_name: sw_team_7_spring_blue
    ports:
      - "8630:8080"
    networks:
      - app-network

  sw_team_7_spring_green:
    image: sw_team_7_spring:latest
    container_name: sw_team_7_spring_green
    ports:
      - "8640:8080"
    networks:
      - app-network

networks:
  app-network:
    external: true