version: '3.8'

services:
  sw_team_7_nginx:
    image: nginx:alpine
    container_name: sw_team_7_nginx
    ports:
      - "8620:80"
    volumes:
      - /home/sw_team_7/deployTest/nginx/conf.d:/etc/nginx/conf.d
      - /home/sw_team_7/deployTest/nginx/upstream:/etc/nginx/upstream
      - /home/sw_team_7/deployTest/nginx/upstream_blue.conf:/etc/nginx/upstream_blue.conf
      - /home/sw_team_7/deployTest/nginx/upstream_green.conf:/etc/nginx/upstream_green.conf
    networks:
      - app-network
    depends_on:
      - sw_team_7_spring_blue
      - sw_team_7_spring_green

  sw_team_7_spring_blue:
    image: sw_team_7_spring:latest
    container_name: sw_team_7_spring_blue
    ports:
      - "8630:8080"
    env_file:
      - .env
    networks:
      - app-network

  sw_team_7_spring_green:
    image: sw_team_7_spring:latest
    container_name: sw_team_7_spring_green
    ports:
      - "8640:8080"
    env_file:
      - .env
    networks:
      - app-network

networks: # 네트워크
  app-network:
    external: true
